# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='isalive',
            field=models.BooleanField(default=False),
        ),
    ]
