# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0002_site_isalive'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ismonitoring',
            field=models.BooleanField(default=True),
        ),
    ]
