# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-14 09:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sitemonitor', '0005_site_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 5, 14, 9, 55, 12, 105247, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
